# Generated by Django 5.2.6 on 2025-09-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.IntegerField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table_comment': 'Cars Table',
            },
        ),
    ]
